#!/bin/bash
# This script is used by the dev-desktop-us-1 instance once a week to benchmark
# Don't use this script directly, use becnh (which is user friendly and all that)

cd becnh || exit 1
if [ -n "$1" ]; then
    bash becnh "$1" "$2"
else
    bash becnh --master
fi
cp rustc-perf/results.db .
git add results.db
git commit -m "Update results.db for $(date +%Y-%m-%d)"
git push

echo "Weekly run is done!"