name: Weekly Clippy Benchmark
on:
#   schedule:
#     - cron: '0 0 * * */5'
  workflow_dispatch:


jobs:
  benchmark_master:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          passphrase: ${{ secrets.PASSPHRASE }}
          key: ${{ secrets.KEY }}
          command_timeout: 2h
          script: bash weekly
